language: node_js
node_js:
  - "10"
deploy:
  provider: heroku
  api_key:
    secure: TaHQ4DxJi+wEze+xPJP3neSTZEwGV6zg4lEzCfnvnBYGG5HazBBFbYK+m+K47cB8SEeHuHQ1sPZUd5FDkxLXrz4FvJ1+hFvWRR+jeAy8EzVBZpqbqn37XaCkKw+CozfKwe4x7jI7knEvkrCIiQWVOSc/wFXWrxlAYbTZbgNkvoM2z/ld34ePCoHPcOe/bgQkRVW6648+BaiRbVpNlat0eZoUSt8DFcst1UrPmqFeEDsL2mNYEM1CQkVMJt4ERlZROggklFzI69c080EMFW5Hca9RVt9FHiDa808skYo9XIUXNHgI85MT3egTQ6doT8VZQBJrxF95hu3JN6FNYM76hcwpNoNaoUGEoXLeimf+CBzIH0SVLxHql0wQTRLHSebP13KYjKTXNjCi94pKn65L8I1RYGo/zJNPWEZwcuUO6wVUw8+lsSCVfHdJNWGaJz94chqPxHmy7LKSunZsmN3+mJyAKWz6kAXPa8VCk0hscIBbvSjfw09Qnek0L7m8EUGC0HRxgGtrnWvFYPw6nyGcxtwdRgl3pLa26vWaeMyLUa+/GUrHDr77tfY+YBI84hfW5nnboTyoK8x0xg5sETg9P/KXwKkeKNh80Oca0om1I3Qu0OL5b1eaIrBq4N5DS5XnmlYkzxCzBBXWoKIxg2NxR2bOZyWmG6cApaLujzxNEdM=
  app: enigmatic-brook-93035
  on:
    repo: rcoedo/runtrack-be
